name = "doodad-video-processor-v2"
main = "video-worker.js"
compatibility_date = "2024-05-17"

# Enable module format
[build.upload]
format = "modules"

# Trigger the worker every 5 minutes to check for jobs
[triggers]
crons = ["*/5 * * * *"]

# Environment variables and bindings
[vars]
R2_BUCKET = "doodad-videos"
SUPABASE_URL = ""  # Set in Cloudflare dashboard
SUPABASE_SERVICE_KEY = ""  # Set in Cloudflare dashboard
OPENAI_API_KEY = ""  # Set in Cloudflare dashboard
API_SECRET = ""  # Secret for triggering manual processing

# Bind to R2 for storage (uncomment when setting up R2)
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "doodad-videos"

# Secret environment variables (set these in the Cloudflare dashboard)
# - R2_ENDPOINT_URL
# - R2_ACCESS_KEY_ID
# - R2_SECRET_ACCESS_KEY

# Environment variables will be set in the dashboard 